typography_spectrum: 0.3631755145035204
color:
  saturation: 0.6830307320734984
  brandStrength: 0.7458244640459445
  lightness: 0.47899312661103166
  brandColors:
    - '#1B52A0'
    - '#25AAE1'
    - '#FFFFFF'
    - '#00409F'
    - '#000080'
  rhythmicContrast: 1
github: true
layout_spectrum: 0.6902116556071888
analytics:
  google: UA-89159147-1
author:
  name: Stuart Millinship
  email: me@stuartm.net
  url: enas
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ef93df29-7d83-45cd-a251-a93dbde24f07.png
name: Everyone Needs A Stuart
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: '"Everyone Needs A Stuart"'
content: []
description: Technology Consultancy and support.
purpose:
  - type: contact
    url: 'tel:07968777058'
    label: Call 07968777058
  - type: contact
    url: 'mailto:me@stuartm.net'
    label: Contact me
